# action.yml
name: 'Cloudformation Guard'
description: 'GitHub action to test your cloudformation templates'
branding:
  icon: 'shield'
  color: 'blue'
inputs:
  input: 
    description: 'Input'
outputs:
  output:
    description: 'Test Output'
runs:
  using: 'docker'
  image: 'Dockerfile'
 